### PR TITLE
move loop invariant variables out from loop to save gas

### PR DESCRIPTION
**Pull request by MollyHe5**
Moving loop invariant codes out from loop can save gas.
In the following demo, it can save 265 units of gas when the length of ```arr``` is 100.

```
function test1(uint256[] memory arr) public {     
        for(uint256 i = 0; i < arr.length; i++) {
        }
    }

    function test2(uint256[] memory arr) public {
        uint256 len = arr.length;
        for(uint256 i = 0; i < len; i++) {
        }
    }
```

### CODE REVIEW

**Comment by songlh** [comment]
@moodysalem @hensha256 @NoahZinsmeister Can you help take a look at this pull request? I think the pull request should be merged, since it can save gases while keeping the original functionality.

**Comment by MollyHe5** [comment]
Initializing variables before the loop instead of inside the loop can also save gas. In the example below, function test4 consumes 553 units less gas than function test3 when the length of arr is 100.
```
    function test3(uint256[] memory arr) public {
        for(uint256 i = 0; i < arr.length; i++) {
            uint256 a = arr[i];
        }
    }

    function test4(uint256[] memory arr) public {
        uint256 a;
        for(uint256 i = 0; i < arr.length; i++) {
            a = arr[i];
        }
    }
```
I committed some changes to move these variable definitions out of the loop.
Can someone take a look?

**Comment by Toluphene** [comment]
Anyway out or solution

**Comment by Toluphene** [comment]
The procedure shows it has been renew and remove from stale

**Pull request closed without merging**
