### PR TITLE
Update IWETH9.sol

### PR DESCRIPTION
**Pull request by garthsun**
change solidity version from '=0.7.6' to '>=0.7.6'

### CODE REVIEW

**Comment by Muniz-colima** [comment]
Y

**Comment by 2twon** [comment]
Need help to reconnect My NFT

**Review by rkarendt — APPROVED** [review]

**Comment by jeffreyschultz** [comment]
There are several files within this repo that need to be updated to also include this change. I am having conflicts with parts of the codebase that import OpenZeppelin, which depends on `^0.8.0`.

**Review by Gemk83 — APPROVED** [review]

**Review by Gemk83 — APPROVED** [review]

**Comment by hensha256** [comment]
Closing in preference of #288 which is the more generalised version of this PR

**Pull request closed without merging**
